title: AabTaab
default_lang: en
author:
  name: 'Joe Bloggs'
  email: joe@example.com
taxonomies:
  - category
  - tag
metadata:
  description: 'AabTaab - Accessible and affordable Shia Islamic online courses and religious services including Niyabat Ziyarat, Zakat, and Khums.'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
redirects: null
routes: null
blog:
  route: /blog
