streams:
  schemes:
    theme:
      type: ReadOnlyStream
      prefixes:
        '': [user/themes/my-quark, user/themes/quark]
enabled: true
production-mode: '1'
grid-size: grid-xl
header-fixed: '1'
header-animated: '1'
header-dark: false
header-transparent: false
sticky-footer: true
blog-page: /blog
spectre:
  exp: true
  icons: true
custom_logo:
  user/themes/quark/images/logo/aabtaab-logo.webp:
    name: aabtaab-logo.webp
    full_path: aabtaab-logo.webp
    type: image/webp
    size: 56746
    path: user/themes/quark/images/logo/aabtaab-logo.webp
custom_logo_mobile:
  user/themes/quark/images/logo/aabtaab-logo.webp:
    name: aabtaab-logo.webp
    full_path: aabtaab-logo.webp
    type: image/webp
    size: 56746
    path: user/themes/quark/images/logo/aabtaab-logo.webp
dropdown:
  enabled: true
brand_primary: '#3b4252'
brand_secondary: '#88c0d0'
brand_accent: '#bf616a'
radius_main: 12px
font_family: Outfit
footer_bg: '#0f0f10'
footer_text: '#ffffff'
footer_accent: '#d4af37'
contact_address: 'R-591 Block 20 F B Area Karachi.'
contact_email: edu.aabtaab@gmail.com
contact_phone: '+92 302 245 2000'
social_links:
  -
    network: twitter
    url: 'https://x.com/aabtaabonline'
  -
    network: facebook
    url: 'https://www.facebook.com/aabtaab/'
  -
    network: youtube
    url: 'https://www.youtube.com/@AabTaab'
  -
    network: instagram
    url: 'https://www.instagram.com/aabtaab_online/'
  -
    network: googlemaps
    url: 'https://maps.app.goo.gl/YUf2yjfbLy1G6uW19'
social_text: '0'
font_primary: Roboto
font_header: 'Playfair Display'
font_size_base: 16
heading_scale: 1.2
logo_height: 48
logo_height_mobile: 32
logo:
  user/themes/my-quark/images/logo/aabtaab-logo.webp:
    name: aabtaab-logo.webp
    full_path: aabtaab-logo.webp
    type: image/webp
    size: 56746
    path: user/themes/my-quark/images/logo/aabtaab-logo.webp
brand_text: Aabtaab
brand_text_show: '1'
background_texture: none
texture_opacity: 1.05
glass_opacity: 0.85
container_width: 1200
spacing_scale: 1
texture_animate: '1'
vignette_overlay: '1'
texture_color: '#93573e'
