streams:
  schemes:
    theme:
      type: ReadOnlyStream
      prefixes:
        '': [user/themes/my-quark, user/themes/quark]
physic_glass_blur: 20
physic_neo_strength: 0.5
physic_neo_lightSource: top-left
enabled: true
haptic_feedback: true
production-mode: '1'
grid-size: grid-xl
header-fixed: '1'
header-animated: '1'
header-dark: '0'
header-transparent: '0'
sticky-footer: '1'
blog-page: /blog
spectre:
  exp: '1'
  icons: '1'

dropdown:
  enabled: true
brand_primary: '#3b4252'
brand_secondary: '#88c0d0'
brand_accent: '#bf616a'
physic_radius_main: 12px
font_family: Outfit
footer_bg: '#0f0f10'
footer_text: '#ffffff'
footer_accent: '#d4af37'
contact_address: 'R-591 Block 20 F B Area Karachi.'
contact_email: edu.aabtaab@gmail.com
contact_phone: '+92 302 245 2000'
social_links:
  -
    network: twitter
    url: 'https://x.com/aabtaabonline'
  -
    network: facebook
    url: 'https://www.facebook.com/aabtaab/'
  -
    network: youtube
    url: 'https://www.youtube.com/@AabTaab'
  -
    network: instagram
    url: 'https://www.instagram.com/aabtaab_online/'
  -
    network: googlemaps
    url: 'https://maps.app.goo.gl/YUf2yjfbLy1G6uW19'
social_text: '0'
font_primary: Roboto
font_header: 'Playfair Display'
font_size_base: 16
heading_scale: 1.2
logo_height: 48
logo_height_mobile: 32

brand_text: Aabtaab
brand_text_show: '1'
background_texture: none
texture_opacity: 1.05
glass_opacity: 0.85
container_width: 1200
spacing_scale: 1
texture_animate: '1'
vignette_overlay: '1'
texture_color: '#93573e'
header_builder:
  -
    type: logo
    text: aabtaab
    link: null
    logo_height: 24
    logo_height_mobile: 18
    visibility: all
    classes: null
    animation: zoomIn
    animation_delay: '0'
    haptic_feedback: '1'
    focus_hide: '0'
footer_builder:
  -
    width: col-4
    type: branding
    title: Aabtaab
    content: null
    animation: fadeUp
footer_copyright: '&copy; 2026 Your Company. All rights reserved.'
footer_credits: 'Designed by Antigravity'
footer_links_title: Links

