enabled: true
production-mode: true
grid-size: grid-xl
header-fixed: true
header-animated: true
header-dark: false
header-transparent: false
sticky-footer: true
blog-page: /blog
spectre:
  exp: true
  icons: true
custom_logo:
  user/themes/quark/images/logo/aabtaab-logo.webp:
    name: aabtaab-logo.webp
    full_path: aabtaab-logo.webp
    type: image/webp
    size: 56746
    path: user/themes/quark/images/logo/aabtaab-logo.webp
custom_logo_mobile:
  user/themes/quark/images/logo/aabtaab-logo.webp:
    name: aabtaab-logo.webp
    full_path: aabtaab-logo.webp
    type: image/webp
    size: 56746
    path: user/themes/quark/images/logo/aabtaab-logo.webp
