title: Services Module
'@extends':
    type: default
    context: blueprints://pages

form:
  fields:
    tabs:
      type: tabs
      active: 1

      fields:
        content:
          type: tab
          title: Content
          fields:
            header.title:
              type: text
              label: Section Title
              default: 'Holistic Support for the Community'
            
            content:
              type: editor
              label: Description

            header.services:
              type: list
              label: Services
              fields:
                .icon:
                  type: icon
                  label: Icon
                .title:
                  type: text
                  label: Title
                .description:
                  type: textarea
                  label: Description
                .link:
                  type: text
                  label: Link
                  default: '#'
                .featured:
                    type: toggle
                    label: Featured (Large Card)
                    highlight: 1
                    default: 0
                    options:
                        1: PLUGIN_ADMIN.YES
                        0: PLUGIN_ADMIN.NO
