enabled: true
production-mode: true
grid-size: grid-xl
header-fixed: true
header-animated: true
header-dark: false
header-transparent: false
sticky-footer: true
blog-page: /blog
spectre:
  exp: true
  icons: true
custom_logo: {  }
custom_logo_mobile: {  }
