enabled: true
dropdown:
  enabled: true
site:
  maxwidth: '1280'
  sectionwrappadding: '20px 20px'
  sectionwrappaddingmobile: '20px 20px'
  favicon:
    user/themes/akazie-forest/custom/images/favicon/faavicon.png:
      name: faavicon.png
      full_path: faavicon.png
      type: image/png
      size: 515422
      path: user/themes/akazie-forest/custom/images/favicon/faavicon.png
header:
  displaylogo: '1'
  javascript: null
  langswitcher:
    position: '0'
  fixed:
    option: true
  closemenucaption: schliessen
  logo:
    desktop:
      user/themes/akazie-forest/custom/images/logo/logo.png:
        name: logo.png
        full_path: logo.png
        type: image/png
        size: 515422
        path: user/themes/akazie-forest/custom/images/logo/logo.png
    mobile: {  }
nav:
  fittocontent: '1'
  navheight: '85'
  hamburger: true
  linksbeforehamburger: 3
  mobileheightenabled: '1'
  mobilelogoenabled: '1'
  customcode: null
  mobilenavheight: '85'
  hamburgercolor: '#7b9b50'
  xcolor: '#7b9b50'
  button:
    enabled: false
    text: null
    link: /
    url: null
footer:
  top:
    bgcolor: '#ffffff'
    color: '#2285c6'
  mail: edu.aabtaab@gmail.com
  phone: '+923022452000'
  bottom:
    enabled: true
    bgcolor: '#5a784d'
    color: '#ffffff'
  copyright:
    enabled: true
    text: 'Copyright Â© Aabtaab 2025. All rights reserved'
  impressum:
    enabled: true
    link: /home
  datenschutz:
    enabled: true
    link: /home
    text: null
  agb:
    enabled: true
    link: /home
    text: ''
  sitemap:
    enabled: true
    link: /home
  showinnav:
    enabled: true
  javascript:
    code: null
top:
  footer:
    socialtext: Facebook
    socials:
      -
        icon: null
        link: null
        fontsize: '0'
style:
  color:
    background:
      main: '#ffffff'
      primary: '#bf202f'
      secondary: '#2285c6'
      third: '#482112'
      tertiary: '#e9ba1d'
    text:
      main: '#707070'
      primary: '#1D1D1D'
      colorlinks: '1'
  fonts:
    import: 'https://fonts.googleapis.com/css?family=Montserrat|Open+Sans|Raleway&display=swap'
    google: '1'
    uploadselect: '0'
    main: '''Open Sans'', sans-serif'
    h: '''Raleway'', sans-serif'
    nav: '''Montserrat'', sans-serif'
    footer: '''Raleway'', sans-serif'
    customhtml: null
  css: false
  js: false
  compress: false
  noresize: false
blog-page: /blog
portfolio-page: /portfolio
