enabled: true
production-mode: false
grid-size: grid-xl
debug_glass: false
direction: ltr
language: en
number_format: western
date_calendar: both
primary_spirit_color: '#2ecc71'
accent_color: '#f1c40f'
font_heading: sans-serif
font_body: "'Outfit-VariableFont_wght', sans-serif"
custom_fonts:
  'Inter-VariableFont_slnt,wght.ttf':
    name: 'Inter-VariableFont_slnt,wght.ttf'
    path: 'user/themes/nur-ul-huda/fonts/custom/Inter-VariableFont_slnt,wght.ttf'
    type: application/octet-stream
    size: 297214
  Outfit-VariableFont_wght.ttf:
    name: Outfit-VariableFont_wght.ttf
    path: user/themes/nur-ul-huda/fonts/custom/Outfit-VariableFont_wght.ttf
    type: application/octet-stream
    size: 110884
  PlusJakartaSans-VariableFont_wght.ttf:
    name: PlusJakartaSans-VariableFont_wght.ttf
    path: user/themes/nur-ul-huda/fonts/custom/PlusJakartaSans-VariableFont_wght.ttf
    type: application/octet-stream
    size: 176288
  PlayfairDisplay-VariableFont_wght.ttf:
    name: PlayfairDisplay-VariableFont_wght.ttf
    path: user/themes/nur-ul-huda/fonts/custom/PlayfairDisplay-VariableFont_wght.ttf
    type: application/octet-stream
    size: 300724
  Merriweather-Regular.ttf:
    name: Merriweather-Regular.ttf
    path: user/themes/nur-ul-huda/fonts/custom/Merriweather-Regular.ttf
    type: application/octet-stream
    size: 297273
  Merriweather-Bold.ttf:
    name: Merriweather-Bold.ttf
    path: user/themes/nur-ul-huda/fonts/custom/Merriweather-Bold.ttf
    type: application/octet-stream
    size: 297238
  NotoNastaliqUrdu-VariableFont_wght.ttf:
    name: NotoNastaliqUrdu-VariableFont_wght.ttf
    path: user/themes/nur-ul-huda/fonts/custom/NotoNastaliqUrdu-VariableFont_wght.ttf
    type: application/octet-stream
    size: 690304
glass_bg_color: '#ffffff'
glass_opacity: 20
glass_blur: 9
glass_border_opacity: 12
glass_highlight: 38
glass_noise: true
header-fixed: true
header-animated: true
header-dark: false
header-transparent: false
header_padding: 1rem
top_banner_enabled: true
top_banner_widgets_order: 'date,prayer,hijri'
top_banner_announcement_enabled: true
top_banner_announcement_bg_color: '#b91c1c'
top_banner_announcement_text_color: '#ffffff'
top_banner_bg_color: '#111827'
top_banner_text_color: '#f1c40f'
prayer_method: karachi
hijri_offset: 0
default_location: Karachi
hero_enabled: true
hero_default_style: hero-large
services_enabled: true
services_default_columns: '3'
features_enabled: true
features_default_layout: standard
gallery_enabled: true
istafta_enabled: true
khums_enabled: true
timeline_enabled: true
trust_signals_enabled: true
courses_enabled: true
bottom_banner_show_social_labels: true
color_error: 'oklch(0.55 0.22 25)'
color_success: 'oklch(0.6 0.15 145)'
color_surface: 'oklch(0.98 0.01 260)'
color_surface_subtle: 'oklch(0.95 0.01 260)'
color_dark: 'oklch(0.15 0.02 260)'
color_text: 'oklch(0.2 0.02 260)'
color_text_muted: 'oklch(0.5 0.02 260)'
color_subtle: 'oklch(0.4 0.02 260)'
color_border: 'oklch(0.85 0.01 260)'
color_border_subtle: 'oklch(0.9 0.01 260)'
glass_thickness: 1
glass_shadow_intensity: 0.1
font_family_base: font-sans
font_size_base: 16
line_height_base: 1.6
container_max_width: max-w-7xl
section_spacing: normal
enable_animations: true
animation_speed: normal
custom_css_variables: ''
sticky-footer: '1'
blog-page: /blog
spectre:
  exp: true
  icons: true
custom_logo:
  user/themes/nur-ul-huda/images/logo/aabtaab-logo.webp:
    name: aabtaab-logo.webp
    full_path: aabtaab-logo.webp
    type: image/webp
    size: 56746
    path: user/themes/nur-ul-huda/images/logo/aabtaab-logo.webp
custom_logo_mobile:
  'user/themes/nur-ul-huda/images/logo/aabtaab-logo (1).svg':
    name: 'aabtaab-logo (1).svg'
    full_path: 'aabtaab-logo (1).svg'
    type: image/svg+xml
    size: 17774
    path: 'user/themes/nur-ul-huda/images/logo/aabtaab-logo (1).svg'
top_banner_show_dates: false
top_banner_show_prayer_ticker: true
top_banner_show_contact: false
top_banner_show_social: false
site_name: aabtaab
site_tagline: 'Guiding is light of faith'
blur_strength: 12
typography: roboto_mono
social_facebook: 'https://www.facebook.com/aabtaab/'
social_twitter: 'https://x.com/aabtaabonline'
social_instagram: 'https://www.instagram.com/aabtaab_online/'
social_youtube: 'https://www.youtube.com/c/aabtaab/'
social_whatsapp: 'https://api.whatsapp.com/send/?phone=923022452000&text=Hi%20there!%20I%27m%20visiting%20aabtaab.com%20and%20have%20a%20few%20questions.%20Could%20you%20help%20me%20out?&type=phone_number&app_absent=0'
social_email: edu.aabtaab@gmail.com
contact_phone: '+92 302 245 2000'
contact_address: 'R-591 , Near Amroha Ground , F.B. Area Block 20 (incholi) Karach Pakistan'
bottom_banner_copyright: null
bottom_banner_show_social: true
footer_copyright: ''
footer_show_social: '1'
moodle_url: null
moodle_token: null
snipcart_key: null
jazzcash_merchant: ahmed
jazzcash_salt: null
adhan_media: {  }
minaret_enabled: true
minaret_announcement_enabled: true
minaret_announcement_text: 'Wiladat Imam Hussain mubarak to all'
minaret_announcement_expires: '10-01-2026 09:05'
minaret_announcement_bg_color: '#b91c1c'
minaret_announcement_text_color: '#ffffff'
minaret_bg_color: '#111827'
minaret_text_color: '#f1c40f'
minaret_show_dates: true
minaret_show_prayer_ticker: true
minaret_show_contact: true
minaret_show_social: true
glass_opacity_initial: 0.05
glass_opacity_scrolled: 0.2
top_banner_announcement_text: 'Ya Hussain'
top_banner_announcement_expires: '13-01-2026 19:50'
header_site_name: Aabtaab
header:
  glass_bg_color: '#050000'
  glass_opacity: 62
  glass_blur: 8px
  glass_border_opacity: 41
dropdown:
  enabled: true
favicon: {  }
social_google_maps: 'https://maps.app.goo.gl/jC5WoemexvgKoA8F6'
social_phone: '+923022452000'
bottom_banner_show_logo: true
bottom_banner_show_site_name: true
bottom_banner_show_tagline: true
bottom_banner_show_social_labels_mobile: false
bottom_banner_show_social_labels_desktop: true
social_facebook_enabled: true
social_twitter_enabled: true
social_instagram_enabled: true
social_youtube_enabled: true
social_telegram_enabled: true
social_linkedin_enabled: true
social_tiktok_enabled: true
social_pinterest_enabled: true
social_snapchat_enabled: true
social_spotify_enabled: true
social_discord_enabled: true
social_google_maps_enabled: true
social_whatsapp_enabled: true
social_phone_enabled: true
social_email_enabled: true
top_banner_ticker_enabled: '0'
top_banner_ticker_speed: 8
bottom_banner_newsletter_enabled: '1'
bottom_banner_newsletter_title: 'Stay Connected'
bottom_banner_newsletter_text: 'Join our spiritual journey for weekly insights.'
bottom_banner_widgets_order: 'brand,social,nav,newsletter,copyright'
top_banner_quotes:
  -
    text: null
    source: null
top_banner_announcement_starts: '13-01-2026 18:29'
top_banner_announcement_speed: 20
top_banner_glass: '0'
top_banner_border: solid
top_banner_announcement_pause: '1'
newsletter_enabled: true
newsletter_title: 'Stay Connected'
newsletter_text: 'Join our spiritual journey for weekly insights.'
social_show_labels_mobile: false
social_show_labels_desktop: false
social_networks:
  -
    network: twitter
    url: 'https://x.com/aabtaabonline'
    enabled: true
  -
    network: facebook
    url: 'https://www.facebook.com/aabtaab/'
    enabled: true
ticker_enabled: false
ticker_text: 'Ya Imam Musa Kazim (A.S.)'
ticker_link: 'https://en.wikipedia.org/wiki/Musa_al-Kazim'
ticker_speed: 20
ticker_pause: '1'
ticker_bg: '#000000'
ticker_color: '#ffcc00'
ticker_new_tab: true
ticker_starts: '14-01-2026 22:41'
ticker_expires: '14-01-2026 22:45'
glass_defaults_enabled: false
liquid_intensity: 0.7
flow_speed: 1
viscosity: 0.5
surface_tension: 0.3
glass_blur_value: 20
