title: "Nur-e-Hidayat"
default_lang: en
author:
  name: "Nur-e-Hidayat Foundation"
  email: "salam@hidayat.org"
taxonomies:
  - category
  - tag
metadata:
  description: "Nur-e-Hidayat - The Digital Sanctum. Learn Shia Islam online with certified scholars from Qom and Najaf. Offering Quran, Fiqh courses, plus authentic Ziyarat, Zakat, and Khums services worldwide."
summary:
  enabled: true
  format: short
  size: 300
  delimiter: "==="
redirects: null
routes: null
blog:
  route: /blog
